name: "pre-release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Pre-release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ncipollo/release-action@v1.16.0
        with:
          allowUpdates: true
          prerelease: true
          draft: false
          omitDraftDuringUpdate: false
          makeLatest: false
          tag: dev
          name: "Development build"
          artifacts: 'proto/*.proto'
          generateReleaseNotes: true

  trigger-doc-update:
    needs: release
    name: "Trigger documentation update"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Trigger repository_dispatch"
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_DOC_REPO_HOOKS }}
          repository: Jelly-RDF/jelly-rdf.github.io
          event-type: publish-docs-dev
